  height: 500
  menubar: false
  toolbar:
    - undo redo bold italic backcolor | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat | help | image  
  plugins:
    - advlist autolink lists link image charmap print preview anchor imagetools
    - searchreplace visualblocks code fullscreen
    - insertdatetime media table paste code help wordcount

